name: Lint
on: [push, pull_request]
jobs:
  lint:
    uses: open-contracting/.github/.github/workflows/lint.yml@main
    with:
      python-version: '3.10'
      standard-maintenance-scripts-extras: cli
      # MyST-Parser is used as a Sphinx extension.
      standard-maintenance-scripts-ignore: MyST-Parser
